version: "3.8"
services:
    frontend:
        container_name: pp_frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend/src:/app/src
            - ./frontend/public:/app/public
        ports:
            - "5173:5173"